name: CI Merge

on:
    push:
      branches:
        - main
        - next

env:
  BUNDLE_PATH: vendor/bundle

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sdk:
    runs-on: macos-14-xlarge
    steps:
      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CERTIFICATEXC }}
          p12-password: ${{ secrets.CERTIFICATEXC_PASS }}
      - uses: actions/checkout@v4
      - name: Build SDK
        run: make build-xcframeworks

  build-docs:
    runs-on: macos-14-xlarge
    steps:
      - uses: actions/checkout@v4
      - name: Build Docs
        run: make build-docs

  finished:
    runs-on: ubuntu-latest
    needs: [build-sdk, build-docs]
    steps:
      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: ${{ failure() }}
        with:
          type: ${{ job.status }}
          job_name: "Merge things busted!"
          url: ${{ secrets.SLACK_WEBHOOK }}